default_agent: agente_strands_agentcore
agents:
  agente_strands_agentcore:
    name: agente_strands_agentcore
    entrypoint: /Users/csarrion/Cline/ARQUITECTURA DE AGENTES/AWS Bedrock AgentCore/agente_strands_streaming/agente_strands_agentcore.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/csarrion/Cline/ARQUITECTURA DE AGENTES/AWS Bedrock AgentCore/agente_strands_streaming
    aws:
      execution_role: arn:aws:iam::701055077130:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-1-85bc388d69
      execution_role_auto_create: false
      account: '701055077130'
      region: eu-west-1
      ecr_repository: 701055077130.dkr.ecr.eu-west-1.amazonaws.com/bedrock-agentcore-agente_strands_agentcore
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agente_strands_agentcore-BFgYot85YJ
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:701055077130:runtime/agente_strands_agentcore-BFgYot85YJ
      agent_session_id: 4e50ee07-cc7b-4fe5-bc60-abfbb24f300b
    codebuild:
      project_name: bedrock-agentcore-agente_strands_agentcore-builder
      execution_role: arn:aws:iam::701055077130:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-1-85bc388d69
      source_bucket: bedrock-agentcore-codebuild-sources-701055077130-eu-west-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
